from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
import os
import json

router = APIRouter(prefix="/api/v1/digest", tags=["Digest"])

@router.get("/watchlist")
def get_watchlist_digest():
    """Return the watchlist digest JSON generated by the nightly cron.
    The file is stored under `frontend_deploy/data/digests/watchlist_digest.json`.
    """
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "frontend_deploy", "data", "digests"))
    path = os.path.join(base_dir, "watchlist_digest.json")
    if not os.path.exists(path):
        raise HTTPException(status_code=404, detail="Watchlist digest not found. Ensure the nightly script has run.")
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return JSONResponse(content=data)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
