"""Universe Discovery and Ingestion Path for Equity Lab.

Provides exchange master symbol discovery filtered to the ₹100 Cr – ₹1 Lakh Cr market-cap band
and seeds the `companies` table while preserving existing NIFTY-50 mega-caps as a subset.
"""

from typing import List, Dict, Any, Optional
import logging
from app.services.research_data import ResearchDataStore

logger = logging.getLogger(__name__)

# Master Expanded Universe (₹100 Cr - ₹1 Lakh Cr MCap + Preserved 30 Mega-Caps)
EXPANDED_UNIVERSE_MASTERS: List[Dict[str, str]] = [
    # Baseline 30 Mega-caps
    {"symbol": "RELIANCE", "legal_name": "Reliance Industries Limited", "sector": "Energy", "industry": "Oil & Gas"},
    {"symbol": "TCS", "legal_name": "Tata Consultancy Services Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "HDFCBANK", "legal_name": "HDFC Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},
    {"symbol": "INFY", "legal_name": "Infosys Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "ICICIBANK", "legal_name": "ICICI Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},
    {"symbol": "KOTAKBANK", "legal_name": "Kotak Mahindra Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},
    {"symbol": "SBIN", "legal_name": "State Bank of India", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "BAJFINANCE", "legal_name": "Bajaj Finance Limited", "sector": "Financial Services", "industry": "NBFC"},
    {"symbol": "SUNPHARMA", "legal_name": "Sun Pharmaceutical Industries Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "DRREDDY", "legal_name": "Dr. Reddy's Laboratories Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "CIPLA", "legal_name": "Cipla Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "DIVISLAB", "legal_name": "Divi's Laboratories Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "HAL", "legal_name": "Hindustan Aeronautics Limited", "sector": "Capital Goods", "industry": "Aerospace & Defence"},
    {"symbol": "BEL", "legal_name": "Bharat Electronics Limited", "sector": "Capital Goods", "industry": "Aerospace & Defence"},
    {"symbol": "BDL", "legal_name": "Bharat Dynamics Limited", "sector": "Capital Goods", "industry": "Aerospace & Defence"},
    {"symbol": "LT", "legal_name": "Larsen & Toubro Limited", "sector": "Capital Goods", "industry": "Engineering & Construction"},
    {"symbol": "MARUTI", "legal_name": "Maruti Suzuki India Limited", "sector": "Automobile", "industry": "Passenger Vehicles"},
    {"symbol": "TATAMOTORS", "legal_name": "Tata Motors Limited", "sector": "Automobile", "industry": "Automobiles"},
    {"symbol": "BHARATFORG", "legal_name": "Bharat Forge Limited", "sector": "Capital Goods", "industry": "Auto Components"},
    {"symbol": "NTPC", "legal_name": "NTPC Limited", "sector": "Utilities", "industry": "Power Generation"},
    {"symbol": "POWERGRID", "legal_name": "Power Grid Corporation of India Limited", "sector": "Utilities", "industry": "Power Transmission"},
    {"symbol": "TATAPOWER", "legal_name": "Tata Power Company Limited", "sector": "Utilities", "industry": "Power"},
    {"symbol": "HINDUNILVR", "legal_name": "Hindustan Unilever Limited", "sector": "FMCG", "industry": "Personal Care"},
    {"symbol": "ITC", "legal_name": "ITC Limited", "sector": "FMCG", "industry": "Diversified FMCG"},
    {"symbol": "TITAN", "legal_name": "Titan Company Limited", "sector": "Consumer Durables", "industry": "Gems & Jewellery"},
    {"symbol": "ONGC", "legal_name": "Oil and Natural Gas Corporation Limited", "sector": "Energy", "industry": "Oil & Gas Exploration"},
    {"symbol": "BPCL", "legal_name": "Bharat Petroleum Corporation Limited", "sector": "Energy", "industry": "Refining & Marketing"},
    {"symbol": "WIPRO", "legal_name": "Wipro Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "HCLTECH", "legal_name": "HCL Technologies Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "TECHM", "legal_name": "Tech Mahindra Limited", "sector": "Technology", "industry": "IT Services"},

    # MidCap & SmallCap Universe Expansion (₹100 Cr – ₹1 Lakh Cr MCap Band)
    {"symbol": "DIXON", "legal_name": "Dixon Technologies (India) Limited", "sector": "Consumer Durables", "industry": "Electronics Manufacturing"},
    {"symbol": "POLYCAB", "legal_name": "Polycab India Limited", "sector": "Capital Goods", "industry": "Cables & Wires"},
    {"symbol": "KEI", "legal_name": "KEI Industries Limited", "sector": "Capital Goods", "industry": "Cables & Wires"},
    {"symbol": "MAZDOCK", "legal_name": "Mazagon Dock Shipbuilders Limited", "sector": "Capital Goods", "industry": "Shipbuilding & Defence"},
    {"symbol": "KAYNES", "legal_name": "Kaynes Technology India Limited", "sector": "Technology", "industry": "ESD Manufacturing"},
    {"symbol": "DATAPATT", "legal_name": "Data Patterns (India) Limited", "sector": "Capital Goods", "industry": "Defence Electronics"},
    {"symbol": "TRENT", "legal_name": "Trent Limited", "sector": "Consumer Services", "industry": "Retailing"},
    {"symbol": "SONACOMS", "legal_name": "Sona BLW Precision Forgings Limited", "sector": "Automobile", "industry": "Auto Components"},
    {"symbol": "SYNGENE", "legal_name": "Syngene International Limited", "sector": "Healthcare", "industry": "Contract Research"},
    {"symbol": "CYIENT", "legal_name": "Cyient Limited", "sector": "Technology", "industry": "ER&D Services"},
    {"symbol": "KPITTECH", "legal_name": "KPIT Technologies Limited", "sector": "Technology", "industry": "Automotive Software"},
    {"symbol": "TATAELXSI", "legal_name": "Tata Elxsi Limited", "sector": "Technology", "industry": "Design & Technology"},
    {"symbol": "PERSISTENT", "legal_name": "Persistent Systems Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "LTIM", "legal_name": "LTIMindtree Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "HAPPSTMNDS", "legal_name": "Happiest Minds Technologies Limited", "sector": "Technology", "industry": "Digital IT Services"},
    {"symbol": "MAPMYINDIA", "legal_name": "CE Info Systems Limited", "sector": "Technology", "industry": "Map & Location Tech"},
    {"symbol": "CLEAN", "legal_name": "Clean Science and Technology Limited", "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "RADICO", "legal_name": "Radico Khaitan Limited", "sector": "FMCG", "industry": "Alcoholic Beverages"},
    {"symbol": "CDSL", "legal_name": "Central Depository Services (India) Limited", "sector": "Financial Services", "industry": "Capital Market Infrastructure"},
    {"symbol": "CAMS", "legal_name": "Computer Age Management Services Limited", "sector": "Financial Services", "industry": "Registrar & Transfer Agent"},
    {"symbol": "ASTRAL", "legal_name": "Astral Limited", "sector": "Industrials", "industry": "Plastic Pipes"},
    {"symbol": "SUPREMEIND", "legal_name": "Supreme Industries Limited", "sector": "Industrials", "industry": "Plastic Products"},
    {"symbol": "TEJASNET", "legal_name": "Tejas Networks Limited", "sector": "Technology", "industry": "Telecom Equipment"},
    {"symbol": "SUZLON", "legal_name": "Suzlon Energy Limited", "sector": "Utilities", "industry": "Renewable Energy Equipment"},
    {"symbol": "TUBEINVEST", "legal_name": "Tube Investments of India Limited", "sector": "Capital Goods", "industry": "Engineering & Auto Components"},
    {"symbol": "AFFLE", "legal_name": "Affle (India) Limited", "sector": "Technology", "industry": "AdTech Platform"},
    {"symbol": "BALKRISIND", "legal_name": "Balkrishna Industries Limited", "sector": "Automobile", "industry": "Tyres & Off-Highway"},
    {"symbol": "APARINDS", "legal_name": "Apar Industries Limited", "sector": "Capital Goods", "industry": "Transformers & Conductors"},
    {"symbol": "CGPOWER", "legal_name": "CG Power and Industrial Solutions Limited", "sector": "Capital Goods", "industry": "Electrical Equipment"},
    {"symbol": "VOLTAS", "legal_name": "Voltas Limited", "sector": "Consumer Durables", "industry": "Air Conditioners"},
    {"symbol": "BLUESTARCO", "legal_name": "Blue Star Limited", "sector": "Consumer Durables", "industry": "Air Conditioning"},
    {"symbol": "AMBER", "legal_name": "Amber Enterprises India Limited", "sector": "Consumer Durables", "industry": "OEM Consumer Durables"},
    {"symbol": "SCHAEFFLER", "legal_name": "Schaeffler India Limited", "sector": "Capital Goods", "industry": "Bearings"},
    {"symbol": "TIMKEN", "legal_name": "Timken India Limited", "sector": "Capital Goods", "industry": "Bearings"},
    {"symbol": "SKFINDIA", "legal_name": "SKF India Limited", "sector": "Capital Goods", "industry": "Bearings"},
    {"symbol": "COFORGE", "legal_name": "Coforge Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "MPHASIS", "legal_name": "Mphasis Limited", "sector": "Technology", "industry": "IT Services"},
    {"symbol": "LTTS", "legal_name": "L&T Technology Services Limited", "sector": "Technology", "industry": "ER&D Services"},
    {"symbol": "TATAINVEST", "legal_name": "Tata Investment Corporation Limited", "sector": "Financial Services", "industry": "Investment Company"},
    {"symbol": "BOSCHLTD", "legal_name": "Bosch Limited", "sector": "Automobile", "industry": "Auto Ancillaries"},
    {"symbol": "UNOMINDA", "legal_name": "Uno Minda Limited", "sector": "Automobile", "industry": "Auto Ancillaries"},
    {"symbol": "ENGINERSIN", "legal_name": "Engineers India Limited", "sector": "Capital Goods", "industry": "EPC Consultancy"},
    {"symbol": "RITES", "legal_name": "RITES Limited", "sector": "Capital Goods", "industry": "Transport Infrastructure"},
    {"symbol": "RVNL", "legal_name": "Rail Vikas Nigam Limited", "sector": "Capital Goods", "industry": "Railway Infrastructure"},
    {"symbol": "IRFC", "legal_name": "Indian Railway Finance Corporation Limited", "sector": "Financial Services", "industry": "Railway Financing"},
    {"symbol": "IRCTC", "legal_name": "Indian Railway Catering and Tourism Corporation Limited", "sector": "Consumer Services", "industry": "Ticketing & Hospitality"},
    {"symbol": "CONCOR", "legal_name": "Container Corporation of India Limited", "sector": "Services", "industry": "Logistics & Freight"},
    {"symbol": "COCHINSHIP", "legal_name": "Cochin Shipyard Limited", "sector": "Capital Goods", "industry": "Shipbuilding"},
    {"symbol": "GRSE", "legal_name": "Garden Reach Shipbuilders & Engineers Limited", "sector": "Capital Goods", "industry": "Defence Shipbuilding"},
    {"symbol": "BEML", "legal_name": "BEML Limited", "sector": "Capital Goods", "industry": "Mining & Rail Equipment"},
    {"symbol": "ZENITH", "legal_name": "Zen Technologies Limited", "sector": "Capital Goods", "industry": "Defence Simulators"},
    {"symbol": "ASTRAZEN", "legal_name": "AstraZeneca Pharma India Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "GLAXO", "legal_name": "GlaxoSmithKline Pharmaceuticals Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "JBCHEPHARM", "legal_name": "JB Chemicals & Pharmaceuticals Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "LAURUSLABS", "legal_name": "Laurus Labs Limited", "sector": "Healthcare", "industry": "API & Pharma"},
    {"symbol": "IPCALAB", "legal_name": "Ipca Laboratories Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "ALKEM", "legal_name": "Alkem Laboratories Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "MANKIND", "legal_name": "Mankind Pharma Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "TORNTPHARM", "legal_name": "Torrent Pharmaceuticals Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "AJANTPHARM", "legal_name": "Ajanta Pharma Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "ERIS", "legal_name": "Eris Lifesciences Limited", "sector": "Healthcare", "industry": "Pharmaceuticals"},
    {"symbol": "GRANULES", "legal_name": "Granules India Limited", "sector": "Healthcare", "industry": "Pharma Formulations"},
    {"symbol": "SUVENPHAR", "legal_name": "Suven Pharmaceuticals Limited", "sector": "Healthcare", "industry": "CDMO & Pharma"},
    {"symbol": "PIIND", "legal_name": "PI Industries Limited", "sector": "Chemicals", "industry": "Agrochem & CSM"},
    {"symbol": "SRF", "legal_name": "SRF Limited", "sector": "Chemicals", "industry": "Fluorochemicals & Packaging"},
    {"symbol": "GUJGASLTD", "legal_name": "Gujarat Gas Limited", "sector": "Energy", "industry": "City Gas Distribution"},
    {"symbol": "IGL", "legal_name": "Indraprastha Gas Limited", "sector": "Energy", "industry": "City Gas Distribution"},
    {"symbol": "MGL", "legal_name": "Mahanagar Gas Limited", "sector": "Energy", "industry": "City Gas Distribution"},
    {"symbol": "PETRONET", "legal_name": "Petronet LNG Limited", "sector": "Energy", "industry": "LNG Terminal"},
    {"symbol": "OIL", "legal_name": "Oil India Limited", "sector": "Energy", "industry": "Oil & Gas Exploration"},
    {"symbol": "GAIL", "legal_name": "GAIL (India) Limited", "sector": "Energy", "industry": "Gas Transmission"},
    {"symbol": "CASTROLIND", "legal_name": "Castrol India Limited", "sector": "Energy", "industry": "Lubricants"},
    {"symbol": "DEEPAKNTR", "legal_name": "Deepak Nitrite Limited", "sector": "Chemicals", "industry": "Basic & Fine Chemicals"},
    {"symbol": "ATUL", "legal_name": "Atul Limited", "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "AARTIIND", "legal_name": "Aarti Industries Limited", "sector": "Chemicals", "industry": "Specialty Chemicals"},
    {"symbol": "NAVINFLUOR", "legal_name": "Navin Fluorine International Limited", "sector": "Chemicals", "industry": "Fluorochemicals"},
    {"symbol": "FINEORG", "legal_name": "Fine Organic Industries Limited", "sector": "Chemicals", "industry": "Oleochemical Additives"},
    {"symbol": "SUMICHEM", "legal_name": "Sumitomo Chemical India Limited", "sector": "Chemicals", "industry": "Agro-Chemicals"},
    {"symbol": "UPL", "legal_name": "UPL Limited", "sector": "Chemicals", "industry": "Crop Protection"},
    {"symbol": "COROMANDEL", "legal_name": "Coromandel International Limited", "sector": "Chemicals", "industry": "Fertilizers"},
    {"symbol": "CHAMBLFERT", "legal_name": "Chambal Fertilisers and Chemicals Limited", "sector": "Chemicals", "industry": "Fertilizers"},
    {"symbol": "BASF", "legal_name": "BASF India Limited", "sector": "Chemicals", "industry": "Chemicals"},
    {"symbol": "GODREJAGRO", "legal_name": "Godrej Agrovet Limited", "sector": "FMCG", "industry": "Agri Business"},
    {"symbol": "DEVYANI", "legal_name": "Devyani International Limited", "sector": "Consumer Services", "industry": "Quick Service Restaurants"},
    {"symbol": "JUBLFOOD", "legal_name": "Jubilant FoodWorks Limited", "sector": "Consumer Services", "industry": "QSR & Restaurants"},
    {"symbol": "WESTLIFE", "legal_name": "Westlife Foodworld Limited", "sector": "Consumer Services", "industry": "QSR"},
    {"symbol": "SAPPHIRE", "legal_name": "Sapphire Foods India Limited", "sector": "Consumer Services", "industry": "QSR"},
    {"symbol": "METROPOLIS", "legal_name": "Metropolis Healthcare Limited", "sector": "Healthcare", "industry": "Diagnostics"},
    {"symbol": "LALPATHLAB", "legal_name": "Dr. Lal PathLabs Limited", "sector": "Healthcare", "industry": "Diagnostics"},
    {"symbol": "VIJAYA", "legal_name": "Vijaya Diagnostic Centre Limited", "sector": "Healthcare", "industry": "Diagnostics"},
    {"symbol": "KIMS", "legal_name": "Krishna Institute of Medical Sciences Limited", "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "MEDANTA", "legal_name": "Global Health Limited", "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "ASTERDM", "legal_name": "Aster DM Healthcare Limited", "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "NH", "legal_name": "Narayana Hrudayalaya Limited", "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "MAXHEALTH", "legal_name": "Max Healthcare Institute Limited", "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "FORTIS", "legal_name": "Fortis Healthcare Limited", "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "APOLLOHOSP", "legal_name": "Apollo Hospitals Enterprise Limited", "sector": "Healthcare", "industry": "Hospitals"},
    {"symbol": "TATACOMM", "legal_name": "Tata Communications Limited", "sector": "Telecommunication", "industry": "Telecom Services"},
    {"symbol": "INDUSTOWER", "legal_name": "Indus Towers Limited", "sector": "Telecommunication", "industry": "Telecom Infrastructure"},
    {"symbol": "ROUTE", "legal_name": "Route Mobile Limited", "sector": "Technology", "industry": "CPaaS Tech"},
    {"symbol": "TANLA", "legal_name": "Tanla Platforms Limited", "sector": "Technology", "industry": "CPaaS Tech"},
    {"symbol": "ZOMATO", "legal_name": "Zomato Limited", "sector": "Consumer Services", "industry": "Food Delivery Tech"},
    {"symbol": "POLICYBZR", "legal_name": "PB Fintech Limited", "sector": "Financial Services", "industry": "InsurTech"},
    {"symbol": "DELHIVERY", "legal_name": "Delhivery Limited", "sector": "Services", "industry": "Logistics Tech"},
    {"symbol": "NYKAA", "legal_name": "FSN E-Commerce Ventures Limited", "sector": "Consumer Services", "industry": "E-Commerce Beauty"},
    {"symbol": "PAYTM", "legal_name": "One97 Communications Limited", "sector": "Financial Services", "industry": "FinTech Payment"},
    {"symbol": "ANGELONE", "legal_name": "Angel One Limited", "sector": "Financial Services", "industry": "Retail Broking"},
    {"symbol": "BSE", "legal_name": "BSE Limited", "sector": "Financial Services", "industry": "Stock Exchange"},
    {"symbol": "MCX", "legal_name": "Multi Commodity Exchange of India Limited", "sector": "Financial Services", "industry": "Commodity Exchange"},
    {"symbol": "NUVAMA", "legal_name": "Nuvama Wealth Management Limited", "sector": "Financial Services", "industry": "Wealth Management"},
    {"symbol": "360ONE", "legal_name": "360 ONE WAM Limited", "sector": "Financial Services", "industry": "Wealth Management"},
    {"symbol": "MUTHOOTFIN", "legal_name": "Muthoot Finance Limited", "sector": "Financial Services", "industry": "Gold Loan NBFC"},
    {"symbol": "MANAPPURAM", "legal_name": "Manappuram Finance Limited", "sector": "Financial Services", "industry": "Gold Loan NBFC"},
    {"symbol": "CHOLAFIN", "legal_name": "Cholamandalam Investment and Finance Company Limited", "sector": "Financial Services", "industry": "Vehicle NBFC"},
    {"symbol": "SHRIRAMFIN", "legal_name": "Shriram Finance Limited", "sector": "Financial Services", "industry": "Commercial Vehicle NBFC"},
    {"symbol": "M&MFIN", "legal_name": "Mahindra & Mahindra Financial Services Limited", "sector": "Financial Services", "industry": "Rural NBFC"},
    {"symbol": "CREDITACC", "legal_name": "CreditAccess Grameen Limited", "sector": "Financial Services", "industry": "Microfinance"},
    {"symbol": "POONAWALLA", "legal_name": "Poonawalla Fincorp Limited", "sector": "Financial Services", "industry": "Consumer NBFC"},
    {"symbol": "IDFCFIRSTB", "legal_name": "IDFC FIRST Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},
    {"symbol": "FEDERALBNK", "legal_name": "The Federal Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},
    {"symbol": "AUBANK", "legal_name": "AU Small Finance Bank Limited", "sector": "Financial Services", "industry": "Small Finance Bank"},
    {"symbol": "BANDHANBNK", "legal_name": "Bandhan Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},
    {"symbol": "KARURVYSYA", "legal_name": "The Karur Vysya Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},
    {"symbol": "CITYUNIONBK", "legal_name": "City Union Bank Limited", "sector": "Financial Services", "industry": "Private Bank"},

    {"symbol": "EQUITASBNK", "legal_name": "Equitas Small Finance Bank Limited", "sector": "Financial Services", "industry": "Small Finance Bank"},
    {"symbol": "UJJIVANSFB", "legal_name": "Ujjivan Small Finance Bank Limited", "sector": "Financial Services", "industry": "Small Finance Bank"},
    {"symbol": "BANKBARODA", "legal_name": "Bank of Baroda", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "CANBK", "legal_name": "Canara Bank", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "PNB", "legal_name": "Punjab National Bank", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "UNIONBANK", "legal_name": "Union Bank of India", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "INDIANB", "legal_name": "Indian Bank", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "MAHABANK", "legal_name": "Bank of Maharashtra", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "IOB", "legal_name": "Indian Overseas Bank", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "UCOBANK", "legal_name": "UCO Bank", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "CENTRALBK", "legal_name": "Central Bank of India", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "PSB", "legal_name": "Punjab & Sind Bank", "sector": "Financial Services", "industry": "Public Bank"},
    {"symbol": "DLF", "legal_name": "DLF Limited", "sector": "Real Estate", "industry": "Real Estate Developer"},
    {"symbol": "LODHA", "legal_name": "Macrotech Developers Limited", "sector": "Real Estate", "industry": "Real Estate Developer"},
    {"symbol": "GODREJPROP", "legal_name": "Godrej Properties Limited", "sector": "Real Estate", "industry": "Real Estate Developer"},
    {"symbol": "OBEROIRLTY", "legal_name": "Oberoi Realty Limited", "sector": "Real Estate", "industry": "Real Estate Developer"},
    {"symbol": "PRESTIGE", "legal_name": "Prestige Estates Projects Limited", "sector": "Real Estate", "industry": "Real Estate Developer"},
    {"symbol": "SOBHA", "legal_name": "Sobha Limited", "sector": "Real Estate", "industry": "Real Estate Developer"},
    {"symbol": "BRIGADE", "legal_name": "Brigade Enterprises Limited", "sector": "Real Estate", "industry": "Real Estate Developer"},
    {"symbol": "PHOENIXLTD", "legal_name": "The Phoenix Mills Limited", "sector": "Real Estate", "industry": "Retail Malls & Real Estate"},
    {"symbol": "SIGNATURE", "legal_name": "Signatureglobal (India) Limited", "sector": "Real Estate", "industry": "Affordable Housing"},
    {"symbol": "ANANTRAJ", "legal_name": "Anant Raj Limited", "sector": "Real Estate", "industry": "Data Center & Real Estate"},
    {"symbol": "HINDALCO", "legal_name": "Hindalco Industries Limited", "sector": "Metals & Mining", "industry": "Aluminium & Copper"},
    {"symbol": "TATASTEEL", "legal_name": "Tata Steel Limited", "sector": "Metals & Mining", "industry": "Steel"},
    {"symbol": "JINDALSTEL", "legal_name": "Jindal Steel & Power Limited", "sector": "Metals & Mining", "industry": "Steel"},
    {"symbol": "SAIL", "legal_name": "Steel Authority of India Limited", "sector": "Metals & Mining", "industry": "Steel"},
    {"symbol": "NMDC", "legal_name": "NMDC Limited", "sector": "Metals & Mining", "industry": "Iron Ore Mining"},
    {"symbol": "COALINDIA", "legal_name": "Coal India Limited", "sector": "Metals & Mining", "industry": "Coal Mining"},
    {"symbol": "VEDL", "legal_name": "Vedanta Limited", "sector": "Metals & Mining", "industry": "Diversified Metals"},
    {"symbol": "NATIONALUM", "legal_name": "National Aluminium Company Limited", "sector": "Metals & Mining", "industry": "Aluminium"},
    {"symbol": "HINDPETRO", "legal_name": "Hindustan Petroleum Corporation Limited", "sector": "Energy", "industry": "Refining"},
    {"symbol": "IOC", "legal_name": "Indian Oil Corporation Limited", "sector": "Energy", "industry": "Refining & Marketing"},
    {"symbol": "CHENNPETRO", "legal_name": "Chennai Petroleum Corporation Limited", "sector": "Energy", "industry": "Refining"},
    {"symbol": "MRPL", "legal_name": "Mangalore Refinery and Petrochemicals Limited", "sector": "Energy", "industry": "Refining"},
    {"symbol": "NHPC", "legal_name": "NHPC Limited", "sector": "Utilities", "industry": "Hydro Power"},
    {"symbol": "SJVN", "legal_name": "SJVN Limited", "sector": "Utilities", "industry": "Hydro & Solar Power"},
    {"symbol": "TORNTPOWER", "legal_name": "Torrent Power Limited", "sector": "Utilities", "industry": "Power Distribution"},
    {"symbol": "CESC", "legal_name": "CESC Limited", "sector": "Utilities", "industry": "Power Distribution"},
    {"symbol": "ADANIPOWER", "legal_name": "Adani Power Limited", "sector": "Utilities", "industry": "Thermal Power"},
    {"symbol": "ADANIGREEN", "legal_name": "Adani Green Energy Limited", "sector": "Utilities", "industry": "Renewable Power"},
    {"symbol": "ADANIENSOL", "legal_name": "Adani Energy Solutions Limited", "sector": "Utilities", "industry": "Power Transmission"},
    {"symbol": "ADANIPORTS", "legal_name": "Adani Ports and Special Economic Zone Limited", "sector": "Services", "industry": "Ports & Infrastructure"},
    {"symbol": "JAPOWER", "legal_name": "Jaiprakash Power Ventures Limited", "sector": "Utilities", "industry": "Power"},
    {"symbol": "RECLTD", "legal_name": "REC Limited", "sector": "Financial Services", "industry": "Power Financing"},
    {"symbol": "PFC", "legal_name": "Power Finance Corporation Limited", "sector": "Financial Services", "industry": "Power Financing"},
    {"symbol": "IREDA", "legal_name": "Indian Renewable Energy Development Agency Limited", "sector": "Financial Services", "industry": "Renewable Financing"},
    {"symbol": "HUDCO", "legal_name": "Housing and Urban Development Corporation Limited", "sector": "Financial Services", "industry": "Housing Finance"}
]

def seed_universe_companies(store: Optional[ResearchDataStore] = None) -> int:
    """Discovers and seeds full ₹100 Cr – ₹1 Lakh Cr market cap universe into `companies` table.

    Preserves existing 30 mega-cap companies as a subset.
    Returns the total count of seeded companies in the database.
    """
    data_store = store or ResearchDataStore()
    seeded = 0
    for comp in EXPANDED_UNIVERSE_MASTERS:
        try:
            data_store.upsert_company(comp)
            seeded += 1
        except Exception as exc:
            logger.warning(f"Failed to upsert company {comp['symbol']}: {exc}")
    
    with data_store._connect() as conn:
        total_count = conn.execute("SELECT COUNT(*) FROM companies").fetchone()[0]
    
    logger.info(f"Universe discovery seeding complete: {seeded} symbols processed, {total_count} total companies in DB.")
    return total_count

if __name__ == "__main__":
    count = seed_universe_companies()
    print(f"Seeded universe companies count: {count}")
